name: travel_plan
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  mysql_client: ^0.0.27
  uuid: ^3.0.7
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.8.2
  intl: ^0.18.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
